### ISSUE TITLE
Getting the following while trying to use the plugin

### ISSUE THREAD

**Issue by nbenja** [mpriatel/mongodb-grails#2]
Caused by: java.lang.NullPointerException: Cannot invoke method size() on null object
    at com.iolog.mongodbtools.MongoMapperModel.setMappedFields(MongoMapperModel.groovy:49)
    at com.iolog.mongodbtools.MongoMapperModel$setMappedFields.callCurrent(Unknown Source)
    at com.iolog.mongodbtools.MongoMapperModel.<init>(MongoMapperModel.groovy:39)
    at com.iolog.mongodbtools.MongoDbWrapper.addMappedClass(MongoDbWrapper.groovy:234)
    at com.iolog.mongodbtools.MongoDbWrapper$addMappedClass.call(Unknown Source)
    at MongodbToolsGrailsPlugin$_closure3_closure8.doCall(MongodbToolsGrailsPlugin.groovy:52)
    at MongodbToolsGrailsPlugin$_closure3.doCall(MongodbToolsGrailsPlugin.groovy:50)

**Comment by mpriatel** [comment]
Looking at the code, I suspect this error is being thrown because the class that is getting mapped doesn't have a 'mongoMappedFields' property, eg:

<pre>
class Address{
     String city
     String country

     static mongoTypeName = "address"
     static mongoMappedFields = [ 'ci':'city' , 'co' : 'country' ]
  }
</pre>


...is this the case?

Either way, I'll throw a more meaningful exception if the class being mapped isn't properly configured.
